### ISSUE TITLE
Module not found: Error: Can't resolve 'scss-loader'

### ISSUE THREAD

**Issue by EvanZ** [koddr/vue-goodshare#1]
Getting the following errors even though I have npm installed scss-loader.
```
ERROR in ./~/vue-goodshare/src/providers/Line.vue
Module not found: Error: Can't resolve 'scss-loader' in '/Users/****/****/node_modules/vue-goodshare/src/providers'
 @ ./~/vue-goodshare/src/providers/Line.vue 3:0-266
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-goodshare/src/VueGoodshare.vue
 @ ./~/vue-goodshare/src/VueGoodshare.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

```

**Comment by koddr** [comment]
Oh, yep. I'm forget to add dependencies for SCSS.
Thanks for reporting!

**Comment by koddr** [comment]
Fix at [0.9.2](https://github.com/koddr/vue-goodshare/releases/tag/0.9.2)

**Comment by EvanZ** [comment]
Sorry, tried using 0.9.2 and still getting peer dependency errors. 

```
ERROR in ./~/vue-goodshare/src/providers/Line.vue
Module not found: Error: Can't resolve 'scss-loader' in '/Users/***/***/node_modules/vue-goodshare/src/providers'
 @ ./~/vue-goodshare/src/providers/Line.vue 3:0-242
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-goodshare/src/VueGoodshare.vue
 @ ./~/vue-goodshare/src/VueGoodshare.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/**.vue
 @ ./src/components/**.vue
 @ ./src/routes.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

```

**Comment by koddr** [comment]
@EvanZ oh, strange. Peer dependencies will be install with update to `vue-goodshare` 0.9.2.

But ok, just install all dependencies manually:

``` bash
$ npm install css-loader sass-loader node-sass vue-style-loader --save-dev
```

**Comment by EvanZ** [comment]
That does not fix the error. Any other idea what might be going on?

**Comment by koddr** [comment]
@EvanZ could you please start and run our example for understand «where is the problem?»:

**Comment by EvanZ** [comment]
I was able to run that and it worked. I thought maybe I needed to upgrade to webpack 3, so I tried that. Still no luck getting it to work with my project though. Just keep getting the same `scss-loader` errors.

**Comment by koddr** [comment]
Hmm.. can you share your Webpack config?

**Comment by EvanZ** [comment]
Here you go:

https://gist.github.com/EvanZ/37848cd428772437c18d50848ca10419

**Comment by koddr** [comment]
@EvanZ yes, thx.

Try to add:

``` js
  {
    test: /\.vue$/,
    loader: "vue-loader",
    options: {
      loaders: {
        scss: 'vue-style-loader!css-loader!sass-loader' // <-- this line
      }
    }
  },

...

plugins: [
  // this block
  new webpack.LoaderOptionsPlugin({
    vue: {
      loaders: {
        scss: 'style!css!sass'
      }
    }
  })
]
```

**Comment by EvanZ** [comment]
Thanks, first part is easy. But second part I'm not sure where to put that. I see this, but it is for production and I am running in dev currently:

```
if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  // http://vue-loader.vuejs.org/en/workflow/production.html
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ])
}
```

**Comment by koddr** [comment]
I’m planning to drop Fontello iconic font and replace them with inline SVG. This can help, if dependencies doesn’t install or working correctly.

Future 1.0.0 release, I think.

**Comment by vlahde** [comment]
I am having this same issue in version 0.9.3

**Comment by lggwettmann** [comment]
Yeah GoodShare's install was great, but I run into 1000 problems now trying to make the Sass loader to run.. Would be great if those Sass dependencies a) would be gone and b) could be mentioned in the docs.

**Comment by koddr** [comment]
@lggwettmann I make it ASAP.

Your PR is welcome :D

**Comment by lggwettmann** [comment]
Thanks @koddr  - highly appreciate it. 

Unfortunately, I have no clue how to fix it or remove the dependency.

**Comment by lggwettmann** [comment]
Yes, still relevant. Still waiting 😉

**Comment by lggwettmann** [comment]
Btw, yes, still relevant if anyone knows how to fix this.
