### ISSUE TITLE
do you have a twitter social share ?

### ISSUE THREAD

**Issue by renztoygwapo** [koddr/vue-goodshare#2]
the plugins looks promising, but I just want to know if there is a twitter social share. Thanks

**Comment by koddr** [comment]
@renztoygwapo 

> On November 20th, 2015, Twitter changed the look of their buttons and removed the share count along with the unofficial and undocumented API endpoint that powered it. Many third-party tweet buttons that used to display share counts stopped working...
> Twitter API v 1.1

`vue-goodshare` support only official data from official APIs of social networks. If any networks don't support native share counter (from their API) — my component also don't support share counter.

But, if you want to add unofficial Twitter share counter, this solution can help you:

* http://opensharecount.com (for each domain, after register)
