### ISSUE TITLE
can you add gmail support?

### ISSUE THREAD

**Issue by xtrimf** [koddr/vue-goodshare#3]

**Comment by koddr** [comment]
Hello.

Yes, future release (1.0.0 I think) will include more features, also share links to Email.

**Comment by mariusa** [comment]
Hello, any updates on email share? 
Subject could be set to the current title of the page.
Sample code:
```
href="'mailto:?subject=' + current_page_title + '&body=%0D%0A%' + window.location.href"
```
Thanks!

**Comment by koddr** [comment]
Added in [1.1.0](https://github.com/koddr/vue-goodshare/releases/tag/1.1.0)
