### ISSUE TITLE
Whatsapp Share link not found on web.whatsapp.com

### ISSUE THREAD

**Issue by dandheedge** [koddr/vue-goodshare#37]
**Describe the bug**
If you try to share using whatsapp share button, it will have an error **page not found**. Because on your library the default open window link for whatsapp is _wa.me_, this link is not working outside the native app. Instead using **web.whatsapp.com/send?text=** for the share_url.

Here, you should change this code 
https://github.com/koddr/vue-goodshare/blob/0fa750da06059a6e9c3da3fa7ea56bc3d17ae483/src/providers/WhatsApp.vue#L59

**Comment by koddr** [comment]
@dandheedge thanks for share! 👍 

I'll fix it by new version today.
