### ISSUE TITLE
Whatsapp Share link not found on Mobile

### ISSUE THREAD

**Issue by mohamedsabil83** [koddr/vue-goodshare#38]
**Describe the bug**
When trying to share a page using Whatsapp in mobile (browser or chrome), it's open the main page (www.whatsapp.com) instead of opening the Whatsapp application itself. But in the desktop browser, it's working as expected by opening the (web.whatsapp.com) and display available contacts to select from.

**To Reproduce**
1. Go to [Sample page](https://kolalal3ab.com/blog/%D8%B4%D8%AF%D8%A7%D8%AF-%D9%82%D9%88%D8%A7%D9%86%D9%8A%D9%86-%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6%D8%A9-%D8%AA%D8%AD%D8%AA-%D8%AD%D9%85%D8%A7%D9%8A%D8%A9-%D8%A7%D9%84%D9%81%D9%8A%D9%81%D8%A7-%D9%88%D9%86%D9%82%D8%A8%D9%84-%D8%A8%D8%AA%D8%AF%D8%AE%D9%84-%D8%AC%D9%87%D8%AA%D9%8A%D9%86-%D9%81%D9%82%D8%B7)
2. Click on the Whatsapp share button.

**Expected behavior**
Open the Whatsapp app in Mobile.

**Smartphone (please complete the following information):**
 - Device: [Samsung S9+]
 - OS: [Android 10]
 - Browser [stock browser, Chrome]

**Comment by koddr** [comment]
@mohamedsabil83 hi! Thx for reporting.

Please, look at this issue #21 

Old way to share via `wa://...` not working now (as I know), therefore we're switched to web version.

**Comment by mohamedsabil83** [comment]
Yes, I know. I need to know why it's working on desktop browsers but not on mobile browsers!!

**Comment by mohamedsabil83** [comment]
Any suggestion to fix that for mobile?

**Comment by koddr** [comment]
@mohamedsabil83 no idea, because (as you can read in issue) it's *not supported* now, only web-redirection.

**Comment by mohamedsabil83** [comment]
Yes, but do you have any idea why it wotks in pc only not mobile?
