### ISSUE TITLE
Refused to execute script from vue-goodshare

### ISSUE THREAD

**Issue by tonywangcn** [koddr/vue-goodshare#6]
## Overview of the problem

Refused to execute script from 'https://www.reddit.com/api/info.json?url=http%3A%2F%2Flocalhost%3A32880%2Fblogs&callback=vue_goodshare_838' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

### Screenshots

![image](https://user-images.githubusercontent.com/3056655/34371644-e641ba6c-eb09-11e7-81f2-5c79efae9a2f.png)

## Steps to Reproduce

1. npm install --save vue-goodshare
2. npm run dev

## Configuration

- System: macOS Sierra, but running in a Debian GNU/Linux 7 docker
- Browser: Updating Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- vue-goodshare: "vue-goodshare": "^0.9.3",

**Comment by koddr** [comment]
@tonywangcn Hi and thanks for using issue's rules 👍 

Did you try to run `vue-goodshare` on real server (not on `localhost`)? This error raise only if you're calling to Reddit API from your `localhost` (as I know with tests).

Please try at real server and write result to us.

**Comment by tonywangcn** [comment]
I host the vue app in netlify with static files generated in my local machine. It's not possible to install phantomjs or headless chrome there, so is there any other solution for such case?

**Comment by koddr** [comment]
@tonywangcn sorry to say, but Reddit doesn't support `localhost` as web server for getting share count. This is standard case for many social networks, because right share statistics (from real web addresses) for analytics are more important.

Hope this help you.

**Comment by tonywangcn** [comment]
@koddr Thanks for your info. But same error happened to the online app.

![image](https://user-images.githubusercontent.com/3056655/34404031-bd7218d8-ebe6-11e7-86e7-18b0810d4a15.png)

**Comment by koddr** [comment]
@tonywangcn okay, I'll check Reddit API for some changes for share counts.
