### ISSUE TITLE
button_design and has_icon not working on Bundle of share elements

### ISSUE THREAD

**Issue by gimyboya** [koddr/vue-goodshare#7]
## Overview of the problem

The directives `button-redesign` and `has_icon`  doesn't seem to work with the bundle element

## Steps to Reproduce

1.
2.
3.

## Configuration

- System: windows 10
- Browser: chrome
- vue-goodshare: 0.9.3

**Comment by koddr** [comment]
@gimyboya Hi. Can you share more info (like in issue rules) for reproduce this? Any screenshots and/or console errors are very helpful!

What's `button-redesign`? `vue-goodshare` have only `button_design` param.

**Comment by gimyboya** [comment]
my bad it's `button_design` it simply don't work on the Bundle component 

```js
// this don't work
<vue-goodshare button_design="outline"></vue-goodshare>
// or this
<vue-goodshare has_icon></vue-goodshare>
// or this
<vue-goodshare button_design="outline" has_icon></vue-goodshare>
has_icon
```

**Comment by gimyboya** [comment]
@koddr

**Comment by koddr** [comment]
Share code to reproduce your case. In my test case (win10, latest chrome/ff) — everything is okay.

Please share your console error trace back.

**Comment by gimyboya** [comment]
@koddr the code is already shared above that's how you reproduce it...
the share buttons appear but `button_design="outline" and `has_icon` doesn't seem to work i have the normal design appearing. and the console is not showing any error apart from this #6

**Comment by koddr** [comment]
@gimyboya Okay, I finally get what you mean.

Unfortunately, `vue-goodshare` bundles have only one `button_design`. This is main idea: if you want fast — get one of bundles "as is", but if you want more custom buttons — create you own bundle with [single share elements](https://koddr.github.io/vue-goodshare/en/using-component-single.html).
