### ISSUE TITLE
Odnoklassniki share button opens deprecated page

### ISSUE THREAD

**Issue by VsevolodChumachenko** [koddr/vue-goodshare#74]
**Describe the bug**
Odnoklassniki share button doesn't work. It opens the page that is deprecated

**To Reproduce**
Add `import VueGoodshareOd from 'vue-goodshare/src/providers/Odnoklassniki.vue';` and use is it on page `<vue-goodshare-od has_icon />`

**Expected behavior**
The button send to correct page

**Comment by koddr** [comment]
@VsevolodChumachenko hi! Thx for report this.

I fixed it at version `1.5.2`.

**Comment by VsevolodChumachenko** [comment]
Thanks. Problem resolved
