### ISSUE TITLE
Fontello 

### ISSUE THREAD

**Issue by glowens** [koddr/vue-goodshare#8]
Icon Colors are getting overwritten

I am using Fontello icons for other parts of my project and this is overwriting the colors of the social icons. 

I have tried to change the location fo the Fontella.css to before and after your script.  Is there a workaround so the colors are not getting overwritten?  Am I missing the obvious?

**Comment by koddr** [comment]
@glowens hm.. it's strange, because vue-goodshare is Vue-component with inline styles in each social provider. All styles have prefix in CSS and was not overwritten before at my projects.

**Comment by glowens** [comment]
Yes strange.  I removed the other call to Fontello and its fine.  I am assuming there is something funny with the way webpack is compling the fonts and vue.

**Comment by torlun** [comment]
I had a similar issue. Icons were getting incorrect icons. I had a fontello font in my own project. Renamed it to a custom font name, then the icons were OK.
