### ISSUE TITLE
Pinterest is missing the image url

### ISSUE THREAD

**Issue by glowens** [koddr/vue-goodshare#9]
## Overview of the problem

Getting Image_url parameter missing with Pinterest.

### Screenshots

![screenshot 2018-01-30 18 55 44](https://user-images.githubusercontent.com/1330064/35598149-a77c668c-05ef-11e8-8d8a-0410ea8d5e64.png)
![screenshot 2018-01-30 18 56 34](https://user-images.githubusercontent.com/1330064/35598144-a0456e9a-05ef-11e8-9777-6124240c171e.png)

## Steps to Reproduce

You can see this in action on https://animalsfirst.com/pets/profile/5a6790483a2d9a04ce7620ee.  
From the console.log the image for Pinterest is undefined.  I have all the proper meta tags and it checks out on the Pinterest url validator.

## Configuration

- System: 
- Browser: Chrome
- vue-goodshare:

**Comment by glowens** [comment]
I believe I found the issue.  

The meta tag for my image is...
<meta name="image" content="https://pathtoimage.com" >

In the provider Pinterest.vue, image is being set to "image.src".  It should be "image.content".

I think the default meta tag is as I have it.  Let me know if I am incorrect.

**Comment by ElFischer** [comment]
Hi @koddr I still have the same issue @glowens has... "page_image" is empty. Has there been an update? Or can you please tell me what I have to change in my meta-info? Thx!
